# Generated by Django 5.2.7 on 2025-10-31 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto', models.CharField(max_length=9)),
                ('creado_em', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='prrofiles/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perifl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_pulso', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('logintude', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='account.perfil')),
            ],
        ),
    ]
